import axios from 'axios';

/**
 * FinRecon AI - Centralized LLM Client
 *
 * Supports Groq (Llama 3.3 70B / 8B) and Anthropic Claude.
 * Automatically chooses Groq if GROQ_API_KEY is present, or Anthropic if ANTHROPIC_API_KEY is present.
 *
 * @param {string} systemPrompt - System-level guidance and constraints.
 * @param {string} userMessage - User input prompt.
 * @param {number} [maxTokens=1024] - Max response tokens.
 * @returns {Promise<string>} Text content generated by the LLM.
 */
export async function callLLM(systemPrompt = '', userMessage = '', maxTokens = 1024) {
  const groqKey = process.env.GROQ_API_KEY;
  const anthropicKey = process.env.ANTHROPIC_API_KEY;

  if (groqKey) {
    return callGroq(systemPrompt, userMessage, maxTokens, groqKey);
  }

  if (anthropicKey) {
    return callAnthropic(systemPrompt, userMessage, maxTokens, anthropicKey);
  }

  throw new Error('Neither GROQ_API_KEY nor ANTHROPIC_API_KEY is configured in .env.');
}

/**
 * Groq Cloud Chat Completion API
 */
async function callGroq(systemPrompt, userMessage, maxTokens, apiKey) {
  const model = process.env.GROQ_MODEL || 'openai/gpt-oss-120b';
  const url = 'https://api.groq.com/openai/v1/chat/completions';

  const messages = [];
  if (systemPrompt) {
    messages.push({ role: 'system', content: systemPrompt });
  }
  messages.push({ role: 'user', content: userMessage });

  const payload = {
    model,
    messages,
    max_tokens: maxTokens,
    temperature: 0.2,
  };

  const headers = {
    Authorization: `Bearer ${apiKey}`,
    'Content-Type': 'application/json',
  };

  const maxRetries = 2;
  let lastError = null;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await axios.post(url, payload, {
        headers,
        timeout: 25000,
      });

      const choice = response.data?.choices?.[0];
      return choice?.message?.content || '';
    } catch (error) {
      lastError = error;
      const status = error.response?.status;
      const isRetryable = status === 429 || (status >= 500 && status < 600);

      if (attempt < maxRetries && isRetryable) {
        const delayMs = Math.pow(2, attempt) * 500;
        console.warn(`[Groq API] Status ${status}. Retrying ${attempt + 1}/${maxRetries} after ${delayMs}ms...`);
        await new Promise(resolve => setTimeout(resolve, delayMs));
      } else {
        break;
      }
    }
  }

  const msg = lastError.response?.data?.error?.message || lastError.message;
  throw new Error(`Groq API Error (${lastError.response?.status || 'Network'}): ${msg}`);
}

/**
 * Anthropic Messages API
 */
async function callAnthropic(systemPrompt, userMessage, maxTokens, apiKey) {
  const model = process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-20241022';
  const url = 'https://api.anthropic.com/v1/messages';

  const payload = {
    model,
    max_tokens: maxTokens,
    system: systemPrompt,
    messages: [{ role: 'user', content: userMessage }],
  };

  const headers = {
    'x-api-key': apiKey,
    'anthropic-version': '2023-06-01',
    'content-type': 'application/json',
  };

  const maxRetries = 2;
  let lastError = null;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await axios.post(url, payload, {
        headers,
        timeout: 30000,
      });

      const contentBlocks = response.data?.content || [];
      return contentBlocks
        .filter(b => b.type === 'text')
        .map(b => b.text)
        .join('');
    } catch (error) {
      lastError = error;
      const status = error.response?.status;
      const isRetryable = status === 429 || (status >= 500 && status < 600);

      if (attempt < maxRetries && isRetryable) {
        const delayMs = Math.pow(2, attempt) * 600;
        console.warn(`[Anthropic API] Status ${status}. Retrying ${attempt + 1}/${maxRetries} after ${delayMs}ms...`);
        await new Promise(resolve => setTimeout(resolve, delayMs));
      } else {
        break;
      }
    }
  }

  const msg = lastError.response?.data?.error?.message || lastError.message;
  throw new Error(`Claude API Error (${lastError.response?.status || 'Network'}): ${msg}`);
}

// Alias callClaude to callLLM for seamless backward compatibility
export const callClaude = callLLM;

export default {
  callLLM,
  callClaude,
};
